// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.0.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.CodeGen.ModelObject.Test
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Globalization;
    using global::System.Linq;

    using global::OBeautifulCode.Cloning.Recipes;
    using global::OBeautifulCode.Equality.Recipes;
    using global::OBeautifulCode.Type;
    using global::OBeautifulCode.Type.Recipes;

    using static global::System.FormattableString;

    [Serializable]
    public partial class ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 : IModel<ModelAllPublicSetReadOnlyDictionaryOfNullableChild2>
    {
        /// <summary>
        /// Determines whether two objects of type <see cref="ModelAllPublicSetReadOnlyDictionaryOfNullableChild2"/> are equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are equal; otherwise false.</returns>
        public static bool operator ==(ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 left, ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 right)
        {
            if (ReferenceEquals(left, right))
            {
                return true;
            }

            if (ReferenceEquals(left, null) || ReferenceEquals(right, null))
            {
                return false;
            }

            var result = left.Equals(right);

            return result;
        }

        /// <summary>
        /// Determines whether two objects of type <see cref="ModelAllPublicSetReadOnlyDictionaryOfNullableChild2"/> are not equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are not equal; otherwise false.</returns>
        public static bool operator !=(ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 left, ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 right) => !(left == right);

        /// <inheritdoc />
        public bool Equals(ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 other)
        {
            if (ReferenceEquals(this, other))
            {
                return true;
            }

            if (ReferenceEquals(other, null))
            {
                return false;
            }

            var result = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty.IsEqualTo(other.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty)
                      && this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty.IsEqualTo(other.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty)
                      && this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty.IsEqualTo(other.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty)
                      && this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty.IsEqualTo(other.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty)
                      && this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty.IsEqualTo(other.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty)
                      && this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty.IsEqualTo(other.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty)
                      && this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty.IsEqualTo(other.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty)
                      && this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty.IsEqualTo(other.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty)
                      && this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty.IsEqualTo(other.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty)
                      && this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty.IsEqualTo(other.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty);

            return result;
        }

        /// <inheritdoc />
        public override bool Equals(object obj) => this == (obj as ModelAllPublicSetReadOnlyDictionaryOfNullableChild2);

        /// <inheritdoc />
        public override int GetHashCode() => HashCodeHelper.Initialize()
            .Hash(this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty)
            .Hash(this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty)
            .Hash(this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty)
            .Hash(this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty)
            .Hash(this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty)
            .Hash(this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty)
            .Hash(this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty)
            .Hash(this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty)
            .Hash(this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty)
            .Hash(this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty)
            .Value;

        /// <inheritdoc />
        public new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 DeepClone() => (ModelAllPublicSetReadOnlyDictionaryOfNullableChild2)this.DeepCloneInternal();

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override ModelAllPublicSetReadOnlyDictionaryOfNullableParent DeepCloneWithParentReadOnlyDictionaryInterfaceOfNullableBoolProperty(IReadOnlyDictionary<bool?, bool?> parentReadOnlyDictionaryInterfaceOfNullableBoolProperty)
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = parentReadOnlyDictionaryInterfaceOfNullableBoolProperty,
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override ModelAllPublicSetReadOnlyDictionaryOfNullableParent DeepCloneWithParentReadOnlyDictionaryInterfaceOfNullableIntProperty(IReadOnlyDictionary<int?, int?> parentReadOnlyDictionaryInterfaceOfNullableIntProperty)
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = parentReadOnlyDictionaryInterfaceOfNullableIntProperty,
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override ModelAllPublicSetReadOnlyDictionaryOfNullableParent DeepCloneWithParentReadOnlyDictionaryInterfaceOfNullableGuidProperty(IReadOnlyDictionary<Guid?, Guid?> parentReadOnlyDictionaryInterfaceOfNullableGuidProperty)
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = parentReadOnlyDictionaryInterfaceOfNullableGuidProperty,
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override ModelAllPublicSetReadOnlyDictionaryOfNullableParent DeepCloneWithParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty(IReadOnlyDictionary<CustomEnum?, CustomEnum?> parentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty)
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = parentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty,
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override ModelAllPublicSetReadOnlyDictionaryOfNullableParent DeepCloneWithParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty(IReadOnlyDictionary<CustomFlagsEnum?, CustomFlagsEnum?> parentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty)
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = parentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty,
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                             };

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty" />.
        /// </summary>
        /// <param name="child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty">The new <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="ModelAllPublicSetReadOnlyDictionaryOfNullableChild2" /> using the specified <paramref name="child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty" /> for <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 DeepCloneWithChild2ReadOnlyDictionaryInterfaceOfNullableBoolProperty(IReadOnlyDictionary<bool?, bool?> child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty)
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty,
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                             };

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty" />.
        /// </summary>
        /// <param name="child2ReadOnlyDictionaryInterfaceOfNullableIntProperty">The new <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="ModelAllPublicSetReadOnlyDictionaryOfNullableChild2" /> using the specified <paramref name="child2ReadOnlyDictionaryInterfaceOfNullableIntProperty" /> for <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 DeepCloneWithChild2ReadOnlyDictionaryInterfaceOfNullableIntProperty(IReadOnlyDictionary<int?, int?> child2ReadOnlyDictionaryInterfaceOfNullableIntProperty)
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = child2ReadOnlyDictionaryInterfaceOfNullableIntProperty,
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                             };

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty" />.
        /// </summary>
        /// <param name="child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty">The new <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="ModelAllPublicSetReadOnlyDictionaryOfNullableChild2" /> using the specified <paramref name="child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty" /> for <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 DeepCloneWithChild2ReadOnlyDictionaryInterfaceOfNullableGuidProperty(IReadOnlyDictionary<Guid?, Guid?> child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty)
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty,
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                             };

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty" />.
        /// </summary>
        /// <param name="child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty">The new <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="ModelAllPublicSetReadOnlyDictionaryOfNullableChild2" /> using the specified <paramref name="child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty" /> for <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 DeepCloneWithChild2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty(IReadOnlyDictionary<CustomEnum?, CustomEnum?> child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty)
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty,
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                             };

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty" />.
        /// </summary>
        /// <param name="child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty">The new <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="ModelAllPublicSetReadOnlyDictionaryOfNullableChild2" /> using the specified <paramref name="child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty" /> for <see cref="Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public ModelAllPublicSetReadOnlyDictionaryOfNullableChild2 DeepCloneWithChild2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty(IReadOnlyDictionary<CustomFlagsEnum?, CustomFlagsEnum?> child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty)
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty,
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        protected override ModelAllPublicSetReadOnlyDictionaryOfNullableParent DeepCloneInternal()
        {
            var result = new ModelAllPublicSetReadOnlyDictionaryOfNullableChild2
                             {
                                 ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty             = this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty            = this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty      = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.DeepClone(),
                                 Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        public override string ToString()
        {
            var result = Invariant($"OBeautifulCode.CodeGen.ModelObject.Test.ModelAllPublicSetReadOnlyDictionaryOfNullableChild2: ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty = {this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty?.ToString() ?? "<null>"}, ParentReadOnlyDictionaryInterfaceOfNullableIntProperty = {this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty?.ToString() ?? "<null>"}, ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty = {this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty?.ToString() ?? "<null>"}, ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty = {this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.ToString() ?? "<null>"}, ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = {this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.ToString() ?? "<null>"}, Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty = {this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty?.ToString() ?? "<null>"}, Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty = {this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty?.ToString() ?? "<null>"}, Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty = {this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty?.ToString() ?? "<null>"}, Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty = {this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty?.ToString() ?? "<null>"}, Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty = {this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty?.ToString() ?? "<null>"}.");

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        public override IReadOnlyList<ValidationFailure> GetValidationFailures(
            ValidationOptions options = null,
            PropertyPathTracker propertyPathTracker = null)
        {
            options = options ?? new ValidationOptions();
            propertyPathTracker = propertyPathTracker ?? new PropertyPathTracker();

            bool stopOnFirstObjectWithFailures;
            switch (options.ValidateUntil)
            {
                case ValidateUntil.FullyTraversed:
                    stopOnFirstObjectWithFailures = false;
                    break;
                case ValidateUntil.FirstInvalidObject:
                    stopOnFirstObjectWithFailures = true;
                    break;
                default:
                    throw new NotSupportedException(Invariant($"This {nameof(ValidateUntil)} is not supported: {options.ValidateUntil}."));
            }

            bool validateProperties;
            switch (options.ValidationScope)
            {
                case ValidationScope.SelfAndProperties:
                    validateProperties = true;
                    break;
                case ValidationScope.SelfOnly:
                    validateProperties = false;
                    break;
                default:
                    throw new NotSupportedException(Invariant($"This {nameof(ValidationScope)} is not supported: {options.ValidationScope}."));
            }

            var result = new List<ValidationFailure>();

            void ValidateProperties()
            {
                IReadOnlyList<ValidationFailure> localValidationFailures;

                localValidationFailures = ValidatableExtensions.GetValidationFailures(this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty, options, propertyPathTracker, nameof(this.ParentReadOnlyDictionaryInterfaceOfNullableBoolProperty));
                result.AddRange(localValidationFailures);
                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return;
                }

                localValidationFailures = ValidatableExtensions.GetValidationFailures(this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty, options, propertyPathTracker, nameof(this.ParentReadOnlyDictionaryInterfaceOfNullableIntProperty));
                result.AddRange(localValidationFailures);
                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return;
                }

                localValidationFailures = ValidatableExtensions.GetValidationFailures(this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty, options, propertyPathTracker, nameof(this.ParentReadOnlyDictionaryInterfaceOfNullableGuidProperty));
                result.AddRange(localValidationFailures);
                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return;
                }

                localValidationFailures = ValidatableExtensions.GetValidationFailures(this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty, options, propertyPathTracker, nameof(this.ParentReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty));
                result.AddRange(localValidationFailures);
                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return;
                }

                localValidationFailures = ValidatableExtensions.GetValidationFailures(this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty, options, propertyPathTracker, nameof(this.ParentReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty));
                result.AddRange(localValidationFailures);
                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return;
                }

                localValidationFailures = ValidatableExtensions.GetValidationFailures(this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty, options, propertyPathTracker, nameof(this.Child2ReadOnlyDictionaryInterfaceOfNullableBoolProperty));
                result.AddRange(localValidationFailures);
                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return;
                }

                localValidationFailures = ValidatableExtensions.GetValidationFailures(this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty, options, propertyPathTracker, nameof(this.Child2ReadOnlyDictionaryInterfaceOfNullableIntProperty));
                result.AddRange(localValidationFailures);
                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return;
                }

                localValidationFailures = ValidatableExtensions.GetValidationFailures(this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty, options, propertyPathTracker, nameof(this.Child2ReadOnlyDictionaryInterfaceOfNullableGuidProperty));
                result.AddRange(localValidationFailures);
                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return;
                }

                localValidationFailures = ValidatableExtensions.GetValidationFailures(this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty, options, propertyPathTracker, nameof(this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomEnumProperty));
                result.AddRange(localValidationFailures);
                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return;
                }

                localValidationFailures = ValidatableExtensions.GetValidationFailures(this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty, options, propertyPathTracker, nameof(this.Child2ReadOnlyDictionaryInterfaceOfNullableCustomFlagsEnumProperty));
                result.AddRange(localValidationFailures);
                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return;
                }
            }

            void ValidateSelf()
            {
                var segmentSeparator = propertyPathTracker.HasSegments ? propertyPathTracker.SegmentSeparator : string.Empty;

                var selfValidationFailures = (this.GetSelfValidationFailures() ?? new SelfValidationFailure[0])
                    .Where(_ => _ != null)
                    .Select(_ =>
                    {
                        var propertyNames = _.PropertyNames.Count > 1
                            ? Invariant($"({string.Join("|", _.PropertyNames)})")
                            : _.PropertyNames.Single();

                        return new ValidationFailure(
                            this.GetType().ToStringReadable(),
                            Invariant($"{propertyPathTracker.FullPath}{segmentSeparator}{propertyNames}"),
                            _.Message);
                    })
                    .ToList();

                result.AddRange(selfValidationFailures);
            }

            if (options.ValidationOrder == ValidationOrder.PropertiesThenSelf)
            {
                if (validateProperties)
                {
                    ValidateProperties();
                }

                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return result;
                }

                ValidateSelf();
            }
            else if (options.ValidationOrder == ValidationOrder.SelfThenProperties)
            {
                ValidateSelf();

                if (stopOnFirstObjectWithFailures && result.Any())
                {
                    return result;
                }

                if (validateProperties)
                {
                    ValidateProperties();
                }
            }
            else
            {
                throw new NotSupportedException(Invariant($"This {nameof(ValidationOrder)} is not supported: {options.ValidationOrder}."));
            }

            return result;
        }

        /// <inheritdoc />
        public override IReadOnlyList<SelfValidationFailure> GetSelfValidationFailures()
        {
            var result = base.GetSelfValidationFailures();

            return result;
        }
    }
}